swagger: "2.0"
info:
  description: This is the Swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger People API

consumes:
  - application/json
produces:
  - application/json

basePath: "/api"

paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: Get all people
      description: Returns a list of all people
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Person"

  /people/{lname}:
    post:
      operationId: people.create
      tags:
        - People
      summary: Create a new person
      description: Creates a person using the last name as key
      parameters:
        - name: lname
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Person"
      responses:
        201:
          description: Person created
          schema:
            $ref: "#/definitions/Person"
        409:
          description: Person already exists
  
    put:
      operationId: people.update
      tags:
        - People
      summary: Update an existing person
      description: Updates fname of the person by last name
      parameters:
        - name: lname
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Person"
      responses:
        200:
          description: Person updated
          schema:
            $ref: "#/definitions/Person"
        404:
          description: Person not found

definitions:
  Person:
    type: object
    required:
      - fname
      - lname
    properties:
      fname:
        type: string
      lname:
        type: string
      timestamp:
        type: string
