swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article

consumes:
  - application/json
produces:
  - application/json

basePath: "/api"

paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: "Lire la liste des personnes"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
